### ISSUE TITLE
allow .fq file extension

### ISSUE THREAD

**Issue by OwenRackham** [morris-lab/CellTagR#1]
Hello. Firstly thanks for a great tool :)

One very brief feature request that might catch others out as it did for us - we always use .fq rather than .fastq as an extension on our sequencing data and it took us a while to realise that this was why we couldn't read in the file to create the whitelist.

**Comment by KaetheKong** [comment]
Hello,

Thank you for using the tool! And thank you for pointing this out! I have just updated the functions to enable .fq file as well as .fastq file. Please let us know if there are any further issues!
