### ISSUE TITLE
how long will it take to generate the sparse count matrix usually

### ISSUE THREAD

**Issue by whosnothungry** [morris-lab/CellTagR#10]
hello,
i am trying CelltagR package with my own data.  My object is 665MB in size, and i am stuck in this line "bam.test.obj <- CellTagMatrixCount(celltag.obj = bam.test.obj, barcodes.file = "./barcodes.tsv")" 
there is no warning and error.
how long will it take to generate the matrix? i am worried that i may have messed up.
thank you

**Comment by whosnothungry** [comment]
i got my matrix finally 😁

**Comment by sam-morris** [comment]
That's great to hear - thanks for the update! We found an issue with our matrix filtering step - we've fixed this, so please update CellTagR. You will not need to regenerate your matrix, only to re-run your matrix from the filtering step: https://github.com/morris-lab/CellTagR#6-additional-filtering (you will have to empty that slot to be able to re-run correctly).
