### ISSUE TITLE
bam.test.obj <- CellTagMatrixCount(celltag.obj = bam.test.obj, barcodes.file = "./barcodes_all.tsv")

### ISSUE THREAD

**Issue by lk754673712** [morris-lab/CellTagR#11]
bam.test.obj <- CellTagMatrixCount(celltag.obj = bam.test.obj, barcodes.file = "./barcodes_all.tsv")
Warning message:
In `[.data.table`(alltagCounts, , `:=`((tagsRemove), NULL)) :
  length(LHS)==0; no columns to delete or assign RHS to.
The above error was reported in this step，I think the number of rows may be exceed the boundary, so how can I deleted some number of rows to adapt to the conditions ? thanks

**Comment by KaetheKong** [comment]
Hello,

Thank you for using CellTagR!

In this step, we are trying to remove CellTags that have zero UMI count across all cells. I think this warning suggests that all CellTags have at least 1 UMI count and nothing is removed . And it should not affect the result matrix construction and downstream analysis. 

Hope this helps! Please let us know if there is any other issues!
Best,
Wenjun

**Comment by lk754673712** [comment]
Can you give me the code of removing CellTags，I'm not proficient in R，thanks again

**Comment by lk754673712** [comment]
I have deleted all cells in which UMI was expressed only once, and the number of rows of bam.parse.rslt[["v1"]] was reduced to 4,543,130, but the same error was still reported

**Comment by KaetheKong** [comment]
As you have mentioned above, I just want to double check - is the following the error reported?
```
Warning message:
In [.data.table(alltagCounts, , :=((tagsRemove), NULL)) :
length(LHS)==0; no columns to delete or assign RHS to.
```
If so, it can be ignored because it is a warning message and it should have successfully produced the matrix in the <celltag object>@raw.count. Please let us know if there are any additional error messages!

Sorry for the confusion and hope this helps!
Best,
Wenjun

**Comment by lk754673712** [comment]
It works fine, but it appears to have not  generated correlation matrix in this step, "bam.test.obj <- JaccardAnalysis(bam.test.obj)", I can generate correlation matrix when I run a single BAM file, but now running two BAM files will not generate it.
