### ISSUE TITLE
Add compatibility for BAM files produced from zUMIs

### ISSUE THREAD

**Issue by dzhang12** [morris-lab/CellTagR#13]
Just wanted to ask if compatibility for BAM files produced from the zUMI pipeline could be added. Cell barcodes are tagged "BC" and UMIs are tagged "UB".

Thanks!

**Comment by KaetheKong** [comment]
Hello,

Thanks for using CellTagR! I added some code to enable zumi pipeline. You can set the `technique` parameter in the `CellTagExtraction` function to be `zumi`. Let us know if it works out!

Best,
Wenjun
