### ISSUE TITLE
Error in JaccardAnalysis: negative length vectors are not allowed

### ISSUE THREAD

**Issue by Hjackl35** [morris-lab/CellTagR#15]
Hi Wenjun,

I have come across another error. This time in the Jaccard function for v2. Are you able to help me investigate this? The error is:

Error in asMethod(object) : negative length vectors are not allowed
Calls: JaccardAnalysis -> as -> asMethod

It occurs in this line from the `JaccardAnalysis()` function: `celltag.obj@jaccard.mtx <- as(Jac, "dgCMatrix")`

As with the previous bug this step ran fine with v1.

Looking online it looks like one possibility is that the merged `data.frame` has exceeded the maximum length that is allowed for a vector in R `2^31 - 1`.

If I run `str(Jac)` then this is the result:

"","x"
"1","Formal class 'dsTMatrix' [package ""Matrix""] with 7 slots"
"2","  ..@ i       : int [1:1835604345] 0 0 1 0 1 2 0 1 2 3 ..."
"3","  ..@ j       : int [1:1835604345] 0 1 1 2 2 2 3 3 3 3 ..."
"4","  ..@ Dim     : int [1:2] 60590 60590"
"5","  ..@ Dimnames:List of 2"
"6","  .. ..$ : chr [1:60590] ""Sample-10_AAACCCAAGCGTACAG-1"" ""Sample-10_AAACCCATCTAAGCCA-1"" ""Sample-10_AAACGAAAGGGAGGAC-1"" ""Sample-10_AAACGAAGTTAACCTG-1"" ..."
"7","  .. ..$ : chr [1:60590] ""Sample-10_AAACCCAAGCGTACAG-1"" ""Sample-10_AAACCCATCTAAGCCA-1"" ""Sample-10_AAACGAAAGGGAGGAC-1"" ""Sample-10_AAACGAAGTTAACCTG-1"" ..."
"8","  ..@ x       : num [1:1835604345] 1 0 1 0 0 1 0 0 0 1 ..."
"9","  ..@ uplo    : chr ""U"""
"10","  ..@ factors : list()"

The binary data in Jac@x has 1,835,604,345 entries, which is close to the `2^31 - 1` limit (2,147,483,647). This means that it could plausibly exceed the limit when added to the bam.test.obj that includes the v1 data, but I can't work out if this is the issue. If it _is_, then has it happened because of erroneous duplication of the data? Or do I need to restart the analysis with data from a subset of my samples?

Thank you,

James

**Comment by Hjackl35** [comment]
Hi Wenjun, 

I am using `fast = TRUE`. I have not tried the slow version but as both use `as(Jac, "dgTMatrix")` I figured the issue would still be there. However, I can double check.

Yes I saw that running out of memory was another possibility. I am submitting to our cluster and I checked the memory usage and it fell within the maximum assigned. But I can increase the max and try again just to be sure.

best, 

James

**Comment by Hjackl35** [comment]
Follow up:

When I run the slow version I get the same error, but in `do.call()` as follows:

Error in do.call(".Call", c(list(method), list(x), list(y), pairwise,  :
  negative length vectors are not allowed
Calls: JaccardAnalysis -> <Anonymous> -> dist -> do.call -> .Call

Also, assigning more memory does not fix the issue.  The error appears as soon as the `as(Jac, "dgTMatrix")` command is given.

**Comment by KaetheKong** [comment]
James,

Thanks for the update!

I think if the `as` function is where it is causing the issue, we could try remove that step and save the matrix as it is to the object since the calculation seems to work fine with the fast version. 

Try loading the jaccard.analysis function as following and see if it resolves the issue with the `as` function (in the fast version) - 

```
JaccardAnalysis <- function(celltag.obj, plot.corr = TRUE, fast = FALSE) {`
  filtered.whitelised.data <- GetCellTagCurrentVersionWorkingMatrix(celltag.obj, "metric.filtered.count")`
  # Calculating the Jaccard matrix
  if (fast) {
    Jac <- proxyC::simil(filtered.whitelised.data, method = "jaccard")
  } else {
    Jac <- proxy::simil(as.matrix(filtered.whitelised.data), method = "Jaccard")
    Jac <- as.matrix(Jac)
  }
  
  if ((!fast) & plot.corr) {
    diag(Jac) <- 1
    corrplot(Jac, method="color", order="hclust", hclust.method ="ward.D2", cl.lim=c(0,1), tl.cex=0.1)
  }
  
  celltag.obj@jaccard.mtx <- Jac
  return(celltag.obj)
}
```

Wenjun

**Comment by Hjackl35** [comment]
Hi Wenjun, 

It ran for much longer this time. However, in the end it failed because Jac is a dsTMatrix rather than dgCMatrix and so can't be loaded into the celltag object. Here is the error:

Error in (function (cl, name, valueClass)  :
  assignment of an object of class “dsTMatrix” is not valid for @‘jaccard.mtx’ in an object of class “CellTag”; is(value, "dgCMatrix") is not TRUE
Calls: JaccardAnalysis -> <Anonymous>

Is it possible to simply change the CellTag object so that it _can_ hold a dsT class matrix or is that going to cause problems later?

James

**Comment by KaetheKong** [comment]
James,

Thanks for running it! I looked into dsTMatrix a little bit and I think it is likely that your matrix is large and exceeds the limit as a full matrix. But I am thinking dsTMatrix is specifically for symmetric matrix, which could have saved space here for the jaccard... I have updated the initiator to give the type "dsTMatrix" to the jaccard matrix. You will have to reinitiate a new CellTag object to make that effective. And below is some code to migrate from the old object to the new object. After the migration, you should be able to run the jaccard and save it as dsTMatrix in the object. I also updated the clone calling part to adapt for dsTMatrix. It shouldn't be an issue! 

```
migrate.to.new.obj <- function(old.ct.obj, new.ct.obj) {
	slots.all <- slotNames(bam.test.obj)
	for (curr.s in slots.all) {
		if (curr.s == "jaccard.mtx") {
			if (nrow(slot(old.ct.obj, curr.s)) > 0) {
				slot(new.ct.obj, curr.s) <- as(slot(old.ct.obj, curr.s), "dsTMatrix")
			}
		} else {
			slot(new.ct.obj, curr.s) <- slot(old.ct.obj, curr.s)
		}
	}
	return(new.ct.obj)
}

new.bam.test.obj <- CellTagObject("test", "<directory>")
new.bam.test.obj <- migrate.to.new.obj(old.ct.obj = bam.test.obj, new.ct.obj = new.bam.test.obj)
```
Let us know if this works!
Wenjun

**Comment by Hjackl35** [comment]
Hi Wenjun, 

This is so cool! Thank you! I had come to the same conclusion after running the `as()` function in isolation (`setAs("dsTMatrix", "dgTMatrix", function(from) from)` and then `as(Jac, "dgTMatrix")`) and receiving this error:

Error in subCsp_cols(x, j, drop = drop) :
  Cholmod error 'problem too large' at file ../Core/cholmod_sparse.c, line 89
Calls: <Anonymous> ... [ -> .as.Tsp -> as -> .class1 -> [ -> [ -> subCsp_cols

I guess it is so large because it is extremely sparse? (https://stackoverflow.com/questions/58302449/what-does-the-cholmod-error-problem-too-large-means-exactly-problem-when-conv)

Thanks so much for coming up with the migration code. I will run it and let you know what happens.

James

**Comment by Hjackl35** [comment]
Hi Wenjun, 

For the migration I received an error in the `as()` function as follows:

Error in as(slot(old.ct.obj, curr.s), "dsTMatrix") :
  no method or default for coercing “dgCMatrix” to “dsTMatrix”
Calls: migrate.to.new.obj -> as

Does this mean that `setAs()` needs to be used to define the conversion?

After reinstalling CellTagR I also tried running the new `JaccardAnalysis()` function on the current bam.test.obj without the migration and it worked. Would using this create problems later on?

James

**Comment by KaetheKong** [comment]
Hi James,

Thank you for the update!

It is great that it worked! I wasn't sure if it would pick the new class settings for the old object but it seems like it just did! I think the migration is not necessary then. I don't think it would create problems later on. I've modified clone calling to use dsTMatrix. So hopefully it won't be too much of an issue.

Let us know if that step works out!
Wenjun

**Comment by Hjackl35** [comment]
Hi Wenjun, 

OK sounds good. I will move forward then.

Just as a point of interest - I have been looking into sparse matrices and according to this page there does not seem to be a default for coercion of dgCMatrix into dsTMatrix, nor the other way around: http://141.13.250.180/R/library/Matrix/html/00Index.html 

Not sure why this is, but I was wondering how `as()` can work in your original `JaccardAnalysis()` function without the default coercion? (when it is not too large). I can't see anywhere where you have defined the coercion parameters using `setAs()`. Am I missing something?

Thanks

James

**Comment by Hjackl35** [comment]
Hi Wenjun, 

The clone calling step worked! However, now the v3 extraction gives me an error - again because the matrix is too large:

Error in .cbind2Csp(x, y) :
  Cholmod error 'problem too large' at file ../Core/cholmod_sparse.c, line 89
Calls: CellTagMatrixCount ... cbind -> cbind2 -> cbind2 -> cbind2sparse -> .cbind2Csp

James

**Comment by KaetheKong** [comment]
Hi James,

Glad the V2 worked out! I have updated the code just now. Please try to set the `replace.option = TRUE` to generate the matrix count as `CellTagMatrixCount(bam.test.obj, "barcode filename", replace.option = TRUE)`. This should resolve the cbind issue for the matrix to be too large. You can set the same parameter as TRUE in the following steps, such as post collapsing function, binarization, and metric filtering, if you are getting the same error while running the original version. Let us know if this works out!

Regarding the dgC to dsT conversion, if the dgCMatrix is symmetric, then I think the `as` function will be able to take the upper triangular matrix of the dgC and that will be the dsT matrix, which is why it is at least half smaller than the dgC. If the dgCMatrix is non-symmetric, then the `as` function will need to be defined because the default can't force symmetry on the matrix. 

Hope this helps!
Wenjun

**Comment by Hjackl35** [comment]
Hi Wenjun, 

It worked! And so did the following steps, at least up until the end of the v3 clone calling. Thanks again for your help.

Just to let you know I had one other small problem but solved it myself. In the CellTagExtraction function I had to set `fill = TRUE ` in `rbind()` in the last few lines of the function. This was because two of my samples had no v3 CellTags (these are time points before v3 was introduced - some of the other samples also should not have v3 CellTags but had at least one false tag and therefore did not cause the error).

I hope that makes sense and is helpful to know.

Thanks!

James

**Comment by KaetheKong** [comment]
James,

Happy to help! Glad it worked. And thanks for pointing that out and I just updated the code! Feel free to let us know if you have any other issues!

Best,
Wenjun
