### ISSUE TITLE
whitelist error

### ISSUE THREAD

**Issue by khandaud15** [morris-lab/CellTagR#16]
Hi, 

I am trying to use the cellTagR to call clones on our three samples. I started my analysis on 3 sample in one go from a bam files, 
at one of the step, I need the whitelist file for v1 sample. can you please let me know how can i get that for all 3 samples. 

Thanks

**Comment by jindalk** [comment]
Hi, CellTag whitelists for all 3 libraries are available here, under the 'Most Abundant Barcodes (90th Percentile)' section: https://www.addgene.org/pooled-library/morris-lab-celltag/
