### ISSUE TITLE
Paired-end reads & multiple fastq files

### ISSUE THREAD

**Issue by deeKal** [morris-lab/CellTagR#18]
Hello!
I was wondering how I should handle fastq files from paired-end sequencing for the whitelisting of cell tags.
Should I consider only the cell tags found in one of the pair of fastq files or all the cell tags? I'm a little confused.
Also I'd appreciate if you could suggest what I should do for multiple fastq files for one sample. Can they be integrated together to a single celltag object?

Thank you!

**Comment by jindalk** [comment]
You can run whitelisting with just Read1 fastq files. How were the two files generated? Are these independent PCR amplifications from the same library? Or the same amplicon sequenced in two different runs?

**Comment by deeKal** [comment]
Thanks for your answer!
I'll reply, but I'm waiting to hear back from the core first.

**Comment by deeKal** [comment]
I wanted to ask one more thing about whitelisting.
The idea is that we want to keep the CellTags that are found in the data most times, right?
This is a file that we need to generate for each sample every time, right?
Since I haven't got an answer on the question yet, I generated a whitelist file for each sample by merging the R1 files and using 0.9 percentile as a cut-off.
Before filtering and whitelisting I start with 1219 cells and 2067 Celltags.
After filtering, I end up with 14 cells and 118 celltags.
Does this sound right to you?

**Comment by deeKal** [comment]
Hello again! So, our Core people replied and they said that the multiple fastq files are a result of the way the sequencer handles the libraries, so the fastqs should just be combined - which is what I did.
That said, I can't understand how I end up with 14 cells. 
If I keep all the reads in the BAM file and not only the ones that align to GFP and CellTag UTR (I run Cellranger again, with a modified genome) I got ~1000 cells from the ~2500 I start with, which seems reasonable, but I'm not sure if these are FPs or not. 
I was wondering if  I do something wrong during aligning, and this is why I don't get many reads aligned to GFP and/or CT UTR. I added the CT UTR fasta that you provide and the GFP sequence from here: https://bit.ly/2H0XK7R which is the sequence that my wet-lab colleague told me is used in the protocol.
Any thought on that is much appreciated! Thanks!

**Comment by jindalk** [comment]
Hi @deeKal The whitelisting step is performed to de-noise CellTag data. CellTag plasmid libraries are created by inserting a random 8 base barcode in the 3' UTR of a GFP reporter. While the theoretical diversity of such a library is quite high (~65k barcodes), practical size is limited by various bottlenecks such as cloning efficiency etc. For each version of the CellTag library, we've estimated true library complexity and identified constituent CellTag barcode sequences. These lists have been made available on the addgene page here: https://www.addgene.org/pooled-library/morris-lab-celltag/

The whitelist generation process is not meant to be run on sequencing reads generated from your single-cell experiment. If you purchased your celltag library from addgene, you can skip the whitelist generation section and directly use the whitelists provided on the page I've linked above for your clone calling analysis. If you believe your CellTag library might have undergone some drift/significant changes in CellTag barcode composition, you can regenerate a whitelist by sequencing the celltag plasmid library itself, following the "Assessment of CellTag library complexity via sequencing" section of this paper: https://www.nature.com/articles/s41596-019-0247-2

Lastly, I would highly recommend only using reads mapping to GFP, CellTag.UTR and unmapped reads for your clone calling analysis.

**Comment by deeKal** [comment]
Hello and thank you for your answer.
Yes, this makes a lot more sense.
I run CellTagR like that and now I start with ~2500 cells per sample as an output from Cellranger and after following all the recommended steps I end up with 400-650 cells per sample. Is it normal to end up with <20% of the initial number of cells? I should mention that >50% of cells are filtered out during the BAM filtering step.
I don't think that anything else seems weird in the QC. So, if this is normal, I guess that if we want more cells we should just sequence more.
Thanks for your help!

**Comment by jindalk** [comment]
The final cell output would really depend on the MOI of transduction and your experimental conditions. You could check expression levels of GFP/ CellTag UTR in the single cell dataset to gauge how well your transduction worked etc. They should be a part of your count matrix, assuming you added them to your genome reference before running cell ranger. Additionally, if you profile only a small fraction of your cell population, you might end up with smaller and fewer clones being captured. The celltag simulator can help you determine the expected clone size distribution in your data, based on your MOI, number of cells profiled etc  You can find it here: http://www.celltag.org/ under Simulator > Clone Size Distribution
