### ISSUE TITLE
Error in JaccardAnalysis

### ISSUE THREAD

**Issue by elisafazz** [morris-lab/CellTagR#19]
Hello!

I have been coming across this error when running the JaccardAnalysis() step on the new CellTag workflow.

Error in as(Jac, "dsTMatrix") : 
  no method or default for coercing “simil” to “dsTMatrix”

I initially thought this was a size issue, although I was able to reproduce the same error with a very small subset of my data. Notably, I am using the "slow" version of the function. I tried a few troubleshooting steps from Issue #15, including migrating my object to a new object with no success. I re-installed CellTagR when I first got the error, and that also did not help.

Please let me know how to best address this error.

Thank you!

**Comment by jindalk** [comment]
Hi, are you able to reproduce this error using the `Demo_V1.Rds` object included in the package?

Alternatively, you could run Jaccard analysis in fast mode and use the following code to plot the correlation plot manually:
```
Jac <- celltag.obj@jaccard.mtx
diag(Jac) <- 1
corrplot(Jac, method = "color", order = "hclust", hclust.method = "ward.D2", cl.lim = c(0, 1), tl.cex = 0.1)
```
