### ISSUE TITLE
CellTagR support for Drop-seq BAM files

### ISSUE THREAD

**Issue by sarshanp** [morris-lab/CellTagR#2]
Dear morris-lab,

Thank you for a great tool. The CellTagR workflow appears to be directed towards 10X-generated BAM files. When following the workflow for CellTag extraction and quantification using Drop-seq BAM files however, I am unable to extract any CellTags. CellTags are present however, since extraction from the R2 fastq file appears successful. The Drop-seq BAM files were generated using the Drop-seq_Alignment_Cookbook. I assume this is due to the bam.process function not being able to parse the BAM tags for cell barcode (XC) and UMI (XM) contained within the Drop-seq BAM file? Will there be support for Drop-seq BAM files in addition to 10X BAM files?

Also, in preparing Drop-seq BAM files for CellTag extraction, if one does not perform alignment using a custom reference (by concatenating the 3' UTR sequence of the CellTag transcript and the GFP coding sequence of the CellTag transcript to the reference genome), will CellTags be lost post-alignment? Is it recommended to keep unmapped reads within the aligned BAM file when not using a custom reference?

Thank you for the support. Much appreciated.

**Comment by babiddy** [comment]
I am not up to date with the details of the current version of the Drop Seq Alignment workflow, but in previous versions, the default output was a BAM file with the unmapped reads removed. Whether you are using a custom reference or not during the alignment I would use the unfiltered BAM file for CellTag extraction. We have used the output from the Drop Seq alignment workflow, but the workflow was modified slightly to ensure the unfiltered BAM file was saved. CellRanger and Drop Seq use different BAM tags for cell barcodes and UMIs so we will need to update the CellTagR workflow to accommodate Drop Seq files. We'll work on this and update the workflow when finished. 

Thanks for the feedback! 

Best,
Brent

**Comment by sarshan94** [comment]
Hi Brent,

Thank you for the update. CellTagExtraction still appears to not extract any CellTags from Drop-seq BAM files. I wonder if this is due to the "technique" argument in the CellTagExtraction function?

Kind regards,

Sarshan

**Comment by KaetheKong** [comment]
Hi Sarshan,

Thank you for using the tool and thanks for the feedback!

The technique parameter is the correct parameter to change to a different technology. For Drop-Seq, use technique = "dropseq" as a part of the input for the extraction. We will update the documentation to incorporate the changes soon.

There were some bugs earlier regarding using a drop-seq bam file. They should be fixed now. We have just tested it on a previous drop-seq BAM file we had and it successfully extracted CellTags with their barcode and UMI. Maybe give the new version a try! We are not quite up-to-date for the format of BAM file produced with the current Drop-seq alignment pipeline. But hope this modification would help! Please let us know if you have any further issues!

Warm regards,
Wenjun

**Comment by sarshan94** [comment]
Thanks Wenjun for the update. The CellTag extraction worked. Much appreciated!

Kind regards,

Sarshan

**Comment by KaetheKong** [comment]
No problem! Glad to hear it worked!
