### ISSUE TITLE
CellTagPostCollapsing returns collapsed.count with 1 row when reading in multiple BAM files

### ISSUE THREAD

**Issue by bc2zb** [morris-lab/CellTagR#6]
Hello, I've run the pipeline on a number of bam files going from 1 to 3, and whenever I attempt to run the pipeline on more than one bam file, `CellTagPostCollapsing` assigns a `collapsed.count` slot with 1 row. During the run of `CellTagPostCollapsing`. I can run the pipeline on my individual bam files without issue, but when I try to include multiple, I run into this. I think that the aggregate function call is missing during the step that combines the results of starcode together, as this warning pops up.

`Aggregate function missing, defaulting to 'length'`

I'm not a `data.table` expert, and I've not tried to tear apart the source yet, but will add on if I figure out anything.

**Comment by KaetheKong** [comment]
Hello,
Thank you for using the tool!

First of all, we have significantly modified our pipeline recently. Please make sure the package is up-to-date. We haven't changed the version number yet. Maybe consider reinstalling with force rewrite. 

Additionally, would you mind providing us more details regarding the error/issue? For instance, which commands were used? And how are the files/filenames organized, like for the collapsing files and the collapsing result files? And would you mind sharing a part of your pre.starcode slot in the object? Maybe we can start from there!

And also check this issue, it might be helpful! - https://github.com/morris-lab/CellTagR/issues/4

Best,
Wenjun

**Comment by bc2zb** [comment]
`system("~/starcode/starcode -s --print-clusters _Sample-1.txt > collapsing_result_Sample-1.txt")
system("~/starcode/starcode -s --print-clusters _Sample-2.txt > collapsing_result_Sample-2.txt")
system("~/starcode/starcode -s --print-clusters _Sample-3.txt > collapsing_result_Sample-3.txt")`

I solved it, initially, I had prefixed sample id to the beginning.
