### ISSUE TITLE
Subscript out of bounds when convertCellTagMatrix2LinkList data

### ISSUE THREAD

**Issue by lk754673712** [morris-lab/CellTagR#7]
Hello, I have tried to tracing my cells using only v1 library, but the error "Error in `*tmp*`[[jj]] : Subscript out of bounds" appears whenever I convert the matrix, I guess the function of convertCellTagMatrix2LinkList  contains v2 and v3 libraries, but I don’t have them in my data. Can you tell me how to run a single library?

**Comment by KaetheKong** [comment]
Hello,
Thanks for using the tool!

If I am understanding the question correctly, the cells only have the V1 library. With only one library, lineage cannot be reconstructed, only clones tracked. And the network construction and visualization part work when multiple versions are present. Please refer to our paper for further explanation - https://www.nature.com/articles/s41586-018-0744-4

Best,
Wenjun

**Comment by lk754673712** [comment]
Hello, Thank you for your reply！
The purpose of our experiment is to track the cells. Because the cells grow slowly and the cycle is very short during the induction process, so we only need one library. What I want to know is how to use single library to track cells. &nbsp;I have analyzed the differential genes before, but I don’t know how to connect them after adding celltag. I don’t know how your pictures in the article are made such as extended data fig. 6a and extended data fig. 9 a,b. This may be bothering you, but I really want to know, can you tell me the general process?



Merry Christmas





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"KaetheKong"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月21日(星期六) 凌晨5:51
收件人:&nbsp;"morris-lab/CellTagR"<CellTagR@noreply.github.com&gt;;
抄送:&nbsp;"蔺楷"<754673712@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [morris-lab/CellTagR] Subscript out of bounds when convertCellTagMatrix2LinkList data (#7)




Hello,
 Thanks for using the tool!
 
If I am understanding the question correctly, the cells only have the V1 library. With only one library, lineage cannot be reconstructed, only clones tracked. And the network construction and visualization part work when multiple versions are present. Please refer to our paper for further explanation - https://www.nature.com/articles/s41586-018-0744-4
 
Best,
 Wenjun

**Comment by sam-morris** [comment]
Hi, hopefully your original issue is solved - I will close this issue. For this question, with only one library you can perform clonal analysis but not construct lineage. Also, be careful with slow-growing cells - they need time to expand for clones to be detected, and to be large enough to yield meaningful data. We have an experimental simulator here: http://celltag.org/ to aid experimental design. For extended figures 6 asnd 9 in the paper - these are simple expression heatmaps and cell clustering - https://satijalab.org/seurat/ has helpful tutorials for similar analyses. Sam.
