### ISSUE TITLE
Running multiple BAM does not seem to capture all cellTags present in the data

### ISSUE THREAD

**Issue by bc2zb** [morris-lab/CellTagR#8]
I have a cell tag experiment with five BAM files. I've attempted to run the pipeline to completion several times, and only find clones in the first file. I noticed that this persists when I change the order of the files as well. When I run each of the BAM files independently, I get completely different number of cell tags except for the first and last bam file. This appears to happen extremely early in the pipeline, before collapsing. If I run `wc -l` on the files produced by the combined approach:

101731 _Sample-1.txt
     46 _Sample-2.txt
    117 _Sample-3.txt
     40 _Sample-4.txt
  71502 _Sample-5.txt

If I do the same, but for the files produced by running `CellTagExtraction`, `CellTagMatrixCount` on each file individually:

 101731 scaf1120_collapsing.txt (_Sample-1)
  49098 scaf1121_collapsing.txt (_Sample-2)
  83778 scaf1122_collapsing.txt (_Sample-3)
  36874 scaf1152_collapsing.txt (_Sample-4)
  71502 scaf1153_collapsing.txt (_Sample-5)

As I mentioned above, the first and last files seem to have the same number of rows, but the middle three are way off and extremely low. I think this was part of the confusion I had from #6 

Is this my data, or do you seem similar issues when running more than two BAM files using the current documentation?

For reference, here is my celltag code for running multiple bam files.

```{r}
library(CellTagR)

ct35_celltag_0 <- CellTagObject("allruns", fastq.bam.directory = "ct35-all/")
ct35_celltag_1 <- CellTagExtraction(celltag.obj = ct35_celltag_0,
                                     celltag.version = "v1")

barcodes_files <- list("/data/capaldobj/CS026448_Beshiri_cell_tagging_2019_december_18/02_PrimaryAnalysisOutput/00_FullCellrangerOutputs/SCAF1120_35-1A-CTL/outs/filtered_feature_bc_matrix/barcodes.tsv.gz",
                    "/data/capaldobj/CS026448_Beshiri_cell_tagging_2019_december_18/02_PrimaryAnalysisOutput/00_FullCellrangerOutputs/SCAF1152_CT35-1-CTL/outs/filtered_feature_bc_matrix/barcodes.tsv.gz",
                    "/data/capaldobj/CS026448_Beshiri_cell_tagging_2019_december_18/02_PrimaryAnalysisOutput/00_FullCellrangerOutputs/SCAF1121_35-2A-CTL/outs/filtered_feature_bc_matrix/barcodes.tsv.gz",
                    "/data/capaldobj/CS026448_Beshiri_cell_tagging_2019_december_18/02_PrimaryAnalysisOutput/00_FullCellrangerOutputs/SCAF1122_35-3A-CTL/outs/filtered_feature_bc_matrix/barcodes.tsv.gz",
                    "/data/capaldobj/CS026448_Beshiri_cell_tagging_2019_december_18/02_PrimaryAnalysisOutput/00_FullCellrangerOutputs/SCAF1153_CT35-2-CTL/outs/filtered_feature_bc_matrix/barcodes.tsv.gz")


Barcode.Aggregate(barcodes_files, "./barcodes_all.tsv")

celltag_whitelist <- "/data/capaldobj/Cell_tagging_prelim_2019_December_09/v1_whitelist.csv"

ct35_celltag_2 <- CellTagMatrixCount(ct35_celltag_1, barcodes.file = "./barcodes_all.tsv")

ct35_celltag_3 <- CellTagDataForCollapsing(ct35_celltag_2, "./collapsing.txt")

system("~/starcode/starcode -s --print-clusters _Sample-1.txt > collapsing_result_Sample-1.txt")
system("~/starcode/starcode -s --print-clusters _Sample-2.txt > collapsing_result_Sample-2.txt")
system("~/starcode/starcode -s --print-clusters _Sample-3.txt > collapsing_result_Sample-3.txt")
system("~/starcode/starcode -s --print-clusters _Sample-4.txt > collapsing_result_Sample-4.txt")
system("~/starcode/starcode -s --print-clusters _Sample-5.txt > collapsing_result_Sample-5.txt")

ct35_celltag_4 <- CellTagDataPostCollapsing(ct35_celltag_3, collapsed.rslt.file = list.files(".", pattern = "collapsing_result_Sample-[1-5].txt$", full.names = T))

ct35_celltag_5 <- SingleCellDataBinatization(ct35_celltag_4, 2)

ct35_celltag_6 <- SingleCellDataWhitelist(ct35_celltag_5, celltag_whitelist)

ct35_celltag_7 <- MetricBasedFiltering(ct35_celltag_6, 20, comparison = "less")
ct35_celltag_8 <- MetricBasedFiltering(ct35_celltag_7, 2, comparison = "greater")

ct35_celltag_9 <- JaccardAnalysis(ct35_celltag_8)
ct35_celltag_9 <- CloneCalling(ct35_celltag_9, 0.7)
```

**Comment by KaetheKong** [comment]
Hello,

First of all, thank you for using the tool!

Through testing, the functions should work for two or more bam files. Testing this on three equivalent bam files, we get the same cell number in the collapsing file for all three bam files using the combined approach. I think the issue might be related to the organization inside of the folder or the order you have put in your barcode.aggregation function. In this current version, a key thing for multiple files to work is to make sure the order of the BAM file that you're reading is the same as the barcodes file order. For example, if your BAM files are reading in the order of scaf1120, scaf1121, scaf1122, scaf1152, scaf1153, then your barcodes files should be in an ordered list in the same order as following:
```
barcodes_files <-  list(
"/data/capaldobj/CS026448_Beshiri_cell_tagging_2019_december_18/02_PrimaryAnalysisOutput/00_FullCellrangerOutputs/SCAF1120_35-1A-CTL/outs/filtered_feature_bc_matrix/barcodes.tsv.gz",
"/data/capaldobj/CS026448_Beshiri_cell_tagging_2019_december_18/02_PrimaryAnalysisOutput/00_FullCellrangerOutputs/SCAF1121_35-2A-CTL/outs/filtered_feature_bc_matrix/barcodes.tsv.gz",
"/data/capaldobj/CS026448_Beshiri_cell_tagging_2019_december_18/02_PrimaryAnalysisOutput/00_FullCellrangerOutputs/SCAF1122_35-3A-CTL/outs/filtered_feature_bc_matrix/barcodes.tsv.gz", 
"/data/capaldobj/CS026448_Beshiri_cell_tagging_2019_december_18/02_PrimaryAnalysisOutput/00_FullCellrangerOutputs/SCAF1152_CT35-1-CTL/outs/filtered_feature_bc_matrix/barcodes.tsv.gz", 
"/data/capaldobj/CS026448_Beshiri_cell_tagging_2019_december_18/02_PrimaryAnalysisOutput/00_FullCellrangerOutputs/SCAF1153_CT35-2-CTL/outs/filtered_feature_bc_matrix/barcodes.tsv.gz")
```
so that the prefix will be able to match the ones generated from the BAM files. 

Additionally, a note to the collapsing file name formating. Please provide a full path to where to save the collapsing file for the current version so that it will be able to pick up the output filename instead of starting with an underscore. 

Hope this helps!
Wenjun

**Comment by bc2zb** [comment]
changing order solved issue
